package:
  name: intervene
  version: "0.6.1"

source:
  fn: intervene-0.6.1.tar.gz
  url: https://pypi.python.org/packages/34/3a/1a833d4772614ba0ec1c5a418c9a73d0dfdaf8c1a5e489960eb8fd7f4aa8/intervene-0.6.1.tar.gz
  md5: f84d6f68283dd50a29b4648dd3321657

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python
    - setuptools
    - pybedtools
    - matplotlib
    - pandas
    - numpy
    - scipy
    - seaborn
    - r
    - r-upsetr

  run:
    - python
    - pybedtools
    - matplotlib
    - pandas
    - numpy
    - scipy
    - seaborn
    - r
    - r-upsetr

test:
  imports:
    - intervene
    - intervene.example_data
    - intervene.example_data.ENCODE_hESC
    - intervene.example_data.Gene_list
    - intervene.example_data.dbSUPER_mm9
    - intervene.modules
    - intervene.modules.pairwise
    - intervene.modules.upset
    - intervene.modules.venn
  commands:
    - intervene --help

about:
  home: https://github.com/asntech/intervene
  license: MIT License
  summary: 'A tool for intersection of multiple gene or genomic region sets and visualization as venn diagrams, UpSet plots or pariwaise heatmaps'
  license_family: MIT
