package:
  name: trackhub
  version: "0.2"

source:
  fn: trackhub-0.2.tar.gz
  url: https://pypi.python.org/packages/97/3b/96aaa04071face951612d18b26da38994dde625951d1e74e44b0e992f5a8/trackhub-0.2.tar.gz
  md5: 83bc928fb178cc3dc8eb02a656616fac

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - trackhub
    - trackhub.test
    - trackhub.test.data

about:
  home: http://github.com/daler/trackhub
  license: "MIT"
  summary: 'Create and manage UCSC track hubs from Python'
